### PR TITLE
Update to move2

### PR DESCRIPTION
**Pull request by bcaneco**
Hiya! These are proposed changes to update the current online version of the app to the move2 package. Please take these as suggestions and feel free to edit the code (or anything else really!!) and e.g. add more unit test. 

Commits describe the implemented changes, which include:
- code structure refactored with a dplyr-flavoured approach
- Sunset and sunrise computed using {suncalc} as {maptools} no longer active
- `timestamp_local` now provided with appropriate timezones (before was incorrectly fixed to UTC)
- column `timestamp_mean_solar` is now of POSIXct type
- added handling of datasets with projected geometries, and of locations falling in geo-political disputed areas
- columns `timestamp_local` and `local_tz` now included in output when `local_details==TRUE` while `local == FALSE`
- csv data exported as artifact is slightly different from previous version, as column names have changed with the move1 -> move2 migration.

I Look forward to hear your thoughts on the proposed changes! :relaxed:

### CODE REVIEW

**Comment by andreakoelzsch** [comment]
Hi @bcaneco, very great that you have adapted this App! I will have a look at it early next week. :)

**Review by andreakoelzsch — APPROVED** [review]
thanks so much for all the thoughtful changes, Bruno! From looking through them there is nothing that I would have done differently, maybe with less dplyr. Thanks, I am learning a lot by this and the App is getting better :)

**Comment by bcaneco** [comment]
Thanks for the feedback Andrea. Yes, nowadays I tend to rely more on tidyverse packages as I find the resulting code much more readable. But I'm mindful of the imposed dependencies and so always make an effort to not overuse them! :)

Cheers!

**Comment by andreakoelzsch** [comment]
@bcaneco Is it better if I continue hosting the App on MoveApps or do you want to?

**Comment by bcaneco** [comment]
Yep, happy for you to keep hosting the app on MoveApps, if you're happy with that. I see myself as a keen contributor to the app!  :)

**Comment by andreakoelzsch** [comment]
happy to keep hosting it, keen is a bit of an understatement, thanks so much! The App is available on MoveApps now, it worked without any problems in my few test runs (the old Add Times... move1 App is deprecated, but will still work in old workflows if you need it). Thanks also for the insight about geopolitical disputes resulting in different time zones. Had never thought of that.

**Comment by bcaneco** [comment]
Re. the multiple TZs in disputed locations, I never thought about it neither! I just stumbled into it while testing over the test sets provided with the template app 👍

**Pull request merged**
